### ISSUE TITLE
Makefile fails because of extra newline

### ISSUE THREAD

**Issue by eserte** [plicease/Term-EditLine#2]
On most of my smokers I see the following build failure:
```
Output from '/usr/bin/make':

"Makefile", line 289: Need an operator
make: fatal errors encountered -- cannot continue
```

The problematic Makefile line looks like this:
```
CCFLAGS = -I/usr/include/editline 
 -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2
```

I guess this is because of a missing chomp() in the `$pkg_config --cflags` call in `Makefile.PL`.

**Comment by eserte** [comment]
A possible fix:
```
diff --git a/Makefile.PL b/Makefile.PL
index 03f6dff..f7f48b5 100644
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -26,7 +26,8 @@ foreach my $pkg_config ($ENV{PKG_CONFIG}, 'pkg-config', 'pkgconf')
   system $pkg_config, '--exists', 'libedit';
   if($? == 0)
   {
-    $ccflags = join ' ', `$pkg_config --cflags libedit`, $ccflags;
+    chomp(my $add_ccflags = `$pkg_config --cflags libedit`);
+    $ccflags = join ' ', $add_ccflags, $ccflags;
     $libs   = `$pkg_config --libs libedit`;
     $alien  = 0;
     last;
```

**Comment by plicease** [comment]
Thanks!  I didn't see this in my testing and am totally unable so far to reproduce it myself, but I think your patch should do the trick.

**Comment by plicease** [comment]
Your patch is included in 0.11 on its way to CPAN now.  Please let me know if this does not resolve the problem.

**Comment by eserte** [comment]
Works now, tried on a freebsd & several linux systems.

**Comment by plicease** [comment]
I believe you just not sure why I wasn't able to reproduce it!  Tried OS X, Debian.  (both using the `pkg-config` path).  Thanks again for the speedy report and the fix as well.

**Comment by eserte** [comment]
Only idea so far: the first token in your perl's ccflags has something which looks like an assignment to make. If a makefile line looks like
```
 -mmacosx-version-min=10.11 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -DPERL_USE_SAFE_PUTENV
```
or
```
 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
```
then it seems that this line is ignored (or, more correctly, a strange variable named "-macosx-version-min" resp. "-D_FILE_OFFSET_BITS" is created and assigned).
